server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8085

